openapi: 3.0.3

info:
  title: Users dummy API
  version: 0.1.0

paths:
  /users:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"

      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
              example:
                - id: e1afccea-5168-4735-84d4-cb96f6fb5d25
                  firstName: Elon
                  lastName: Musk
                - id: 472063cc-4c83-11ec-81d3-0242ac130003
                  firstName: Sergey
                  lastName: Brin

  /users/{userId}:
    get:
      parameters:
        - in: path
          name: userId
          description: ''
          required: true
          schema:
            type: string

      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: object
      required:
        - id
        - firstName
        - lastName
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
        lastName:
          type: string
