version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    reviewers:
      - "neotoolkit/team"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - "neotoolkit/team"
