version: '3'

tasks:
  default:
    cmds:
      - task: tidy
      - task: lint
      - task: test
      - task: fmt

  tidy:
    - go mod tidy

  lint:
    - golangci-lint run

  test:
    - go test ./test/...

  fmt:
    - go fmt ./...
