version: '3'

tasks:
  default:
    cmds:
      - task: tidy
      - task: fmt
      - task: lint
      - task: test

  tidy:
    - go mod tidy

  fmt:
    - go fmt ./...

  lint:
    - golangci-lint run

  test:
    - go test ./test/...
