version: '3'

tasks:
  default:
    cmds:
      - task: tidy
      - task: fmt
      - task: imports
      - task: lint
      - task: test

  tidy:
    - go mod tidy

  fmt:
    - go fmt ./...

  imports:
    - goimports -local github.com/go-dummy/dummy/ -w -l ./

  lint:
    - golangci-lint run

  test:
    - go test ./test/...
