name: CI

on: pull_request

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: latest
    continue-on-error: true

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.5
      - name: Tests
        run: |
          gem install pact-provider-verifier
          go test -v -race -covermode atomic -coverprofile=coverage.txt ./internal/...
      - name: Upload coverage report
        run: bash <(curl -s https://codecov.io/bash)
