name: Coverage

on:
  pull_request:
    paths-ignore:
      - 'examples/**'
      - '**.md'

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.5
      - name: Tests
        run: |
          go test -race -covermode=atomic -coverprofile=coverage.txt ./internal/...
      - name: Upload coverage report
        run: bash <(curl -s https://codecov.io/bash)
